# Generated by Django 5.1.6 on 2025-03-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='main_events',
        ),
    ]
