# Generated by Django 5.1.6 on 2025-03-12 14:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_event_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField()),
                ('reservetions', ckeditor.fields.RichTextField()),
                ('opening_hours', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
