# Generated by Django 5.1.6 on 2025-03-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_reservations_alter_contact_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='reservetions',
            new_name='reservations',
        ),
    ]
